baseurl      = "https://leandrodaher.com/"
title        = "Leandro Daher"
defaultContentLanguage = "pt-br"
theme        = "hugo-theme-hello-friend-ng"
paginate     = 10

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Software Developer"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  defaultContentLanguageInSubdir = false

  # Metadata mostly used in document's head
  description = "Leandro Daher Website"
  keywords = "leandrodaher, dhrleandro, development, go, golang, php, typescript, javascript, node.js, react.js, homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.pt-br]
    languageCode = "pt-br"
    # contentDir = "content/pr-br"
    languageName = 'Brazilian Portuguese'
    weight = 1
    title = "Leandro Daher"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.pt-br.params]
      keywords = ""
      subtitle  = "leandrodaher.com"
      readOtherPosts = "Leia outras postagens"

      [languages.pt-br.params.logo]
        logoText = "leandrodaher.com"
        logoHomeLink = "/"
        # or
        #
        # path = "/img/your-example-logo.svg"
        # alt = "Your example logo alt text"

  [languages.en]
    languageCode = "en"
    # contentDir = "content/en"
    languageName = 'English'
    weight = 2
    title = "Leandro Daher"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

    [languages.en.params]
      keywords = ""
      subtitle  = "leandrodaher.com"
      readOtherPosts = "Read other posts"

      [languages.en.params.logo]
        logoText = "leandrodaher.com"
        logoHomeLink = "/"
        # or
        #
        # path = "/img/your-example-logo.svg"
        # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"